### ISSUE TITLE
Magisk 17 - stopped working

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/ssh#1]
Hello!
I believe that the module stopped working after Magisk 17.0 update.
The issue might be the removal of /magisk symlink.

```
C:\Users\User\Desktop\platform-tools>adb shell /sbin/.core/img/ssh/opensshd.init start
starting /magisk/ssh/usr/bin/sshd... /sbin/.core/img/ssh/opensshd.init: Error 127 starting /magisk/ssh/usr/bin/sshd... bailing.
/sbin/.core/img/ssh/opensshd.init[90]: /magisk/ssh/usr/bin/sshd: not found
```
All the best!

**Comment by ghost** [comment]
Fixed in 171. Sorry for premature comment.

**Comment by The-MAZZTer** [comment]
I am seeing this bug using Magisk 17.3 on my Pixel 3 XL running Android 9.0 Nov 2018.

**Comment by Fisummer** [comment]
i also come up with this issue and on latest magisk 18.0 for my moto z2 force running Anroid 8.0
