### ISSUE TITLE
Server refused key?

### ISSUE THREAD

**Issue by davidrozen76** [Magisk-Modules-Repo/ssh#15]
So I installed Magisk and the ssh module on a stock firmware Galaxy S7,

I generated a private/public keypair using puttygen, pasted the public key in /data/ssh/.ssh/root/authorized_keys and used the generated private key in putty in order to connect to root@<ip of phone>, but server keeps refusing my key.

I have used this module numerous times and suddenly, now, it doesn't work.

Any ideas?

**Comment by jflassche** [comment]
Exactly the same issue on a Moto G6 plus
Keys generated using linux and working on other systems.

**Comment by davidrozen76** [comment]
@bobribbon solved by chmod 0600 authozrized_keys
