### ISSUE TITLE
/data/ssh/shell should by CHOWNed by shell user

### ISSUE THREAD

**Issue by The-MAZZTer** [Magisk-Modules-Repo/ssh#2]
When I installed the module it was chowned by root. I could not log on as shell via ssh until I chowned the directory to shell. It looks like sshd was unable to read ,ssh/authorized_keys until I did so.

**Comment by D4rCM4rC** [comment]
This should have been fixed in v0.5 on 2018-11-04 (https://github.com/Magisk-Modules-Repo/ssh/commit/51890cbeda5e0a1b5083ee61c8955d23054a7c39#diff-56755ef7919deca2e30854b110f67bde). Did you happen to install v0.4?

**Comment by The-MAZZTer** [comment]
Cool, that's all I need to know.
