### ISSUE TITLE
Can't login - android 10

### ISSUE THREAD

**Issue by mb300sd** [Magisk-Modules-Repo/ssh#22]
I can't login as root or shell. It works on my old phone, but not my new one with Android 10.

Placed key in both /data/ssh/root/.ssh/authorized_keys and /data/ssh/shell/.ssh/authorized_keys

chmodded both to 0600.

Is there a way to see the ssh log?

**Comment by jbsky** [comment]
Hello,

Please, connect with adb shell, and check your file if has a the format. I look my public key in authorized_keys files with a space between each charactere. So, it can't working...


Best regard.

Julien

**Comment by mb300sd** [comment]
Oh, I forgot to close this.

My dumb a** was SSHing the wrong device the whole time.
