### ISSUE TITLE
MODDIR problem

### ISSUE THREAD

**Issue by kenzanin** [Magisk-Modules-Repo/ssh#3]
dear maintainer team

i have to change MODDIR path from /magisk/ssh to /sbin/.core/img/ssh in the opensshd.init file to make the script to work
#: ${MODDIR:=/magisk/ssh}
: ${MODDIR:=/sbin/.core/img/ssh}

device: xiaomi redmi note 3
magisk: 18 stable
os: mokee 7.1

thanks

**Comment by D4rCM4rC** [comment]
Starting with v0.7, opensshd.init derives the MODDIR from its path (just like service.sh does), this way we don't have to hardcode any paths.
