### ISSUE TITLE
unable to use scp: library "libcrypto.so.1.0.0" not found

### ISSUE THREAD

**Issue by lemmy04** [Magisk-Modules-Repo/ssh#5]
I'm trying to use scp to transfer files to my phone but all I get is this error:
CANNOT LINK EXECUTABLE "scp": CANNOT LINK EXECUTABLE "scp": library "libcrypto.so.1.0.0" not found

rsync works...

Running Magisk 18, Android 8.0.0 on a Galaxy S8+

Any ideas?

**Comment by D4rCM4rC** [comment]
Apparently, I've never tried scp before.
In v0.7 I've now added a wrapper script that sets the `LD_LIBRARY_PATH`. This way, scp works and the other few executables like ssh-keygen can be used without having to set the environment variable manually.
