### ISSUE TITLE
/magisk/ssh/opensshd.init start

### ISSUE THREAD

**Issue by revbby** [Magisk-Modules-Repo/ssh#6]
If you are manually start/stopping the sshd-service, `/opensshd.init start` won't work. Running the service script will, by using `/magisk/ssh/service.sh start`. You will however need to give the script file execute permission. You can do this at a terminal by changing the working directory; `cd /magisk/ssh` , and then assigning the execute permission to the script file `chmod +x service.sh`. OR you can do all this on a file explorer with root access.

**Comment by D4rCM4rC** [comment]
Starting with v0.7, opensshd.init derives the MODDIR from its path (just like service.sh does), this way we don't have to hardcode any paths.
