### ISSUE TITLE
SSHD is not starting/running because execute permission is not set for files in raw directory

### ISSUE THREAD

**Issue by gu5t3r** [Magisk-Modules-Repo/ssh#8]
SSHD is not starting/running because execute permission is not set for files in raw directory

Missing in config.sh after copying files and making links:
set_perm_recursive  $MODPATH/usr/bin/raw  0  0  0755  0755

[config_fixed.txt](https://github.com/Magisk-Modules-Repo/ssh/files/2985973/config_fixed.txt)

**Comment by D4rCM4rC** [comment]
Yep. Should be fixed in v0.8.
